# Generated by Django 4.1.5 on 2023-01-18 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('model_of_product', models.CharField(max_length=255, verbose_name='Модель продукта')),
                ('release', models.DateTimeField(null=True, verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': ('Продукт',),
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=254, verbose_name='Город')),
                ('street', models.CharField(max_length=300, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('arrears', models.FloatField(default=0.0, verbose_name='Задолженность')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего обновления')),
                ('object_type', models.PositiveSmallIntegerField(choices=[(1, 'Фабрика'), (2, 'Дистрибьютор'), (3, 'Дилерский центр'), (4, 'Большая розничная сеть'), (5, 'Индивидуальный предприниматель')], verbose_name='Тип объекта')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_task_api.products', verbose_name='Продукты компании')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_task_api.object', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Объект сети',
                'verbose_name_plural': 'Объекты сети',
            },
        ),
    ]
